select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select AVG("Purchase Amount (USD)") from customer)

--Q3. which are the top 5 products with the highest average review rating?
select "Item Purchased", ROUND(AVG("Review Rating"::numeric),2) as "Average Product Rating"
from customer
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5;

--Q4. Compare the average purchase amounts between standard and express shipping.
select "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"

--Q5. Do subcribed customers spend more? compare average spend and total revenue between subcribers and non-subcribers.
SELECT "Subscription Status",
COUNT("Customer ID") AS total_customers,
ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_spend,
ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by "Item Purchased"
order by discount_rate DESC
limit 5;

--Q7. Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select "Customer ID", "Previous Purchases",
CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
	WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer	
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT 
"Category",
"Item Purchased",
COUNT("Customer ID") AS total_orders,
ROW_NUMBER() OVER (
PARTITION BY "Category"
ORDER BY COUNT("Customer ID") DESC
        ) AS item_rank
FROM customer
GROUP BY "Category", "Item Purchased"
)

SELECT  item_rank, "Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select "Subscription Status",
count("Customer ID") as repeat_buyers
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

--Q10. What is the revenue contribution of each age group?
SELECT 
    CASE 
        WHEN "Age" < 25 THEN 'Young'
        WHEN "Age" BETWEEN 25 AND 40 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    
    SUM("Purchase Amount (USD)") AS total_revenue

FROM customer

GROUP BY age_group

ORDER BY total_revenue DESC;
